ERROR - 2023-08-01 01:43:09 --> Error connecting to the database: mysqli_sql_exception: No se puede establecer una conexión ya que el equipo de destino denegó expresamente dicha conexión in C:\xampp\htdocs\proyectosistema\system\Database\MySQLi\Connection.php:174
Stack trace:
#0 C:\xampp\htdocs\proyectosistema\system\Database\MySQLi\Connection.php(174): mysqli->real_connect('localhost', 'dscriptn_root', 'AkJkSzpj123', 'dscriptn_db_sis...', 3306, '', 0)
#1 C:\xampp\htdocs\proyectosistema\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\proyectosistema\system\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\proyectosistema\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\xampp\htdocs\proyectosistema\system\Model.php(840): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\proyectosistema\app\Models\Users.php(21): CodeIgniter\Model->__call('get', Array)
#6 C:\xampp\htdocs\proyectosistema\app\Controllers\Login.php(24): App\Models\Users->obtenerUsuario('admin123')
#7 C:\xampp\htdocs\proyectosistema\system\CodeIgniter.php(934): App\Controllers\Login->acceder()
#8 C:\xampp\htdocs\proyectosistema\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Login))
#9 C:\xampp\htdocs\proyectosistema\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp\htdocs\proyectosistema\index.php(67): CodeIgniter\CodeIgniter->run()
#11 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: No se puede establecer una conexión ya que el equipo de destino denegó expresamente dicha conexión in C:\xampp\htdocs\proyectosistema\system\Database\MySQLi\Connection.php:218
Stack trace:
#0 C:\xampp\htdocs\proyectosistema\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\proyectosistema\system\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\proyectosistema\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 C:\xampp\htdocs\proyectosistema\system\Model.php(840): CodeIgniter\Database\BaseBuilder->get()
#4 C:\xampp\htdocs\proyectosistema\app\Models\Users.php(21): CodeIgniter\Model->__call('get', Array)
#5 C:\xampp\htdocs\proyectosistema\app\Controllers\Login.php(24): App\Models\Users->obtenerUsuario('admin123')
#6 C:\xampp\htdocs\proyectosistema\system\CodeIgniter.php(934): App\Controllers\Login->acceder()
#7 C:\xampp\htdocs\proyectosistema\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Login))
#8 C:\xampp\htdocs\proyectosistema\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\proyectosistema\index.php(67): CodeIgniter\CodeIgniter->run()
#10 {main}
CRITICAL - 2023-08-01 01:43:09 --> Unable to connect to the database.
Main connection [MySQLi]: No se puede establecer una conexión ya que el equipo de destino denegó expresamente dicha conexión
in SYSTEMPATH\Database\BaseConnection.php on line 427.
 1 SYSTEMPATH\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `usuarios`
WHERE `usuario` = :usuario:', [...], false)
 3 SYSTEMPATH\Model.php(840): CodeIgniter\Database\BaseBuilder->get()
 4 APPPATH\Models\Users.php(21): CodeIgniter\Model->__call('get', [])
 5 APPPATH\Controllers\Login.php(24): App\Models\Users->obtenerUsuario('admin123')
 6 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Login->acceder()
 7 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Login))
 8 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
ERROR - 2023-08-01 01:43:21 --> Error connecting to the database: mysqli_sql_exception: No se puede establecer una conexión ya que el equipo de destino denegó expresamente dicha conexión in C:\xampp\htdocs\proyectosistema\system\Database\MySQLi\Connection.php:174
Stack trace:
#0 C:\xampp\htdocs\proyectosistema\system\Database\MySQLi\Connection.php(174): mysqli->real_connect('localhost', 'dscriptn_root', 'AkJkSzpj123', 'dscriptn_db_sis...', 3306, '', 0)
#1 C:\xampp\htdocs\proyectosistema\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\proyectosistema\system\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\proyectosistema\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\xampp\htdocs\proyectosistema\system\Model.php(840): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\proyectosistema\app\Models\Users.php(21): CodeIgniter\Model->__call('get', Array)
#6 C:\xampp\htdocs\proyectosistema\app\Controllers\Login.php(24): App\Models\Users->obtenerUsuario('admin123')
#7 C:\xampp\htdocs\proyectosistema\system\CodeIgniter.php(934): App\Controllers\Login->acceder()
#8 C:\xampp\htdocs\proyectosistema\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Login))
#9 C:\xampp\htdocs\proyectosistema\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp\htdocs\proyectosistema\index.php(67): CodeIgniter\CodeIgniter->run()
#11 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: No se puede establecer una conexión ya que el equipo de destino denegó expresamente dicha conexión in C:\xampp\htdocs\proyectosistema\system\Database\MySQLi\Connection.php:218
Stack trace:
#0 C:\xampp\htdocs\proyectosistema\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\proyectosistema\system\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\proyectosistema\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 C:\xampp\htdocs\proyectosistema\system\Model.php(840): CodeIgniter\Database\BaseBuilder->get()
#4 C:\xampp\htdocs\proyectosistema\app\Models\Users.php(21): CodeIgniter\Model->__call('get', Array)
#5 C:\xampp\htdocs\proyectosistema\app\Controllers\Login.php(24): App\Models\Users->obtenerUsuario('admin123')
#6 C:\xampp\htdocs\proyectosistema\system\CodeIgniter.php(934): App\Controllers\Login->acceder()
#7 C:\xampp\htdocs\proyectosistema\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Login))
#8 C:\xampp\htdocs\proyectosistema\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\proyectosistema\index.php(67): CodeIgniter\CodeIgniter->run()
#10 {main}
CRITICAL - 2023-08-01 01:43:21 --> Unable to connect to the database.
Main connection [MySQLi]: No se puede establecer una conexión ya que el equipo de destino denegó expresamente dicha conexión
in SYSTEMPATH\Database\BaseConnection.php on line 427.
 1 SYSTEMPATH\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `usuarios`
WHERE `usuario` = :usuario:', [...], false)
 3 SYSTEMPATH\Model.php(840): CodeIgniter\Database\BaseBuilder->get()
 4 APPPATH\Models\Users.php(21): CodeIgniter\Model->__call('get', [])
 5 APPPATH\Controllers\Login.php(24): App\Models\Users->obtenerUsuario('admin123')
 6 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Login->acceder()
 7 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Login))
 8 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
ERROR - 2023-08-01 01:43:37 --> Error connecting to the database: ErrorException: mysqli::real_connect(): Error while reading greeting packet. PID=13220 in C:\xampp\htdocs\proyectosistema\system\Database\MySQLi\Connection.php:174
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'mysqli::real_co...', 'C:\\xampp\\htdocs...', 174)
#1 C:\xampp\htdocs\proyectosistema\system\Database\MySQLi\Connection.php(174): mysqli->real_connect('localhost', 'dscriptn_root', 'AkJkSzpj123', 'dscriptn_db_sis...', 3306, '', 0)
#2 C:\xampp\htdocs\proyectosistema\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#3 C:\xampp\htdocs\proyectosistema\system\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
#4 C:\xampp\htdocs\proyectosistema\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#5 C:\xampp\htdocs\proyectosistema\system\Model.php(840): CodeIgniter\Database\BaseBuilder->get()
#6 C:\xampp\htdocs\proyectosistema\app\Models\Users.php(21): CodeIgniter\Model->__call('get', Array)
#7 C:\xampp\htdocs\proyectosistema\app\Controllers\Login.php(24): App\Models\Users->obtenerUsuario('admin123')
#8 C:\xampp\htdocs\proyectosistema\system\CodeIgniter.php(934): App\Controllers\Login->acceder()
#9 C:\xampp\htdocs\proyectosistema\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Login))
#10 C:\xampp\htdocs\proyectosistema\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\proyectosistema\index.php(67): CodeIgniter\CodeIgniter->run()
#12 {main}

Next mysqli_sql_exception: MySQL server has gone away in C:\xampp\htdocs\proyectosistema\system\Database\MySQLi\Connection.php:174
Stack trace:
#0 C:\xampp\htdocs\proyectosistema\system\Database\MySQLi\Connection.php(174): mysqli->real_connect('localhost', 'dscriptn_root', 'AkJkSzpj123', 'dscriptn_db_sis...', 3306, '', 0)
#1 C:\xampp\htdocs\proyectosistema\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\proyectosistema\system\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\proyectosistema\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\xampp\htdocs\proyectosistema\system\Model.php(840): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\proyectosistema\app\Models\Users.php(21): CodeIgniter\Model->__call('get', Array)
#6 C:\xampp\htdocs\proyectosistema\app\Controllers\Login.php(24): App\Models\Users->obtenerUsuario('admin123')
#7 C:\xampp\htdocs\proyectosistema\system\CodeIgniter.php(934): App\Controllers\Login->acceder()
#8 C:\xampp\htdocs\proyectosistema\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Login))
#9 C:\xampp\htdocs\proyectosistema\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp\htdocs\proyectosistema\index.php(67): CodeIgniter\CodeIgniter->run()
#11 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: MySQL server has gone away in C:\xampp\htdocs\proyectosistema\system\Database\MySQLi\Connection.php:218
Stack trace:
#0 C:\xampp\htdocs\proyectosistema\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\proyectosistema\system\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\proyectosistema\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 C:\xampp\htdocs\proyectosistema\system\Model.php(840): CodeIgniter\Database\BaseBuilder->get()
#4 C:\xampp\htdocs\proyectosistema\app\Models\Users.php(21): CodeIgniter\Model->__call('get', Array)
#5 C:\xampp\htdocs\proyectosistema\app\Controllers\Login.php(24): App\Models\Users->obtenerUsuario('admin123')
#6 C:\xampp\htdocs\proyectosistema\system\CodeIgniter.php(934): App\Controllers\Login->acceder()
#7 C:\xampp\htdocs\proyectosistema\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Login))
#8 C:\xampp\htdocs\proyectosistema\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\proyectosistema\index.php(67): CodeIgniter\CodeIgniter->run()
#10 {main}
CRITICAL - 2023-08-01 01:43:37 --> Unable to connect to the database.
Main connection [MySQLi]: MySQL server has gone away
in SYSTEMPATH\Database\BaseConnection.php on line 427.
 1 SYSTEMPATH\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `usuarios`
WHERE `usuario` = :usuario:', [...], false)
 3 SYSTEMPATH\Model.php(840): CodeIgniter\Database\BaseBuilder->get()
 4 APPPATH\Models\Users.php(21): CodeIgniter\Model->__call('get', [])
 5 APPPATH\Controllers\Login.php(24): App\Models\Users->obtenerUsuario('admin123')
 6 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Login->acceder()
 7 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Login))
 8 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
ERROR - 2023-08-01 01:49:34 --> Error connecting to the database: ErrorException: mysqli::real_connect(): Error while reading greeting packet. PID=13220 in C:\xampp\htdocs\proyectosistema\system\Database\MySQLi\Connection.php:174
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'mysqli::real_co...', 'C:\\xampp\\htdocs...', 174)
#1 C:\xampp\htdocs\proyectosistema\system\Database\MySQLi\Connection.php(174): mysqli->real_connect('localhost', 'dscriptn_root', 'AkJkSzpj123', 'dscriptn_db_sis...', 3306, '', 0)
#2 C:\xampp\htdocs\proyectosistema\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#3 C:\xampp\htdocs\proyectosistema\system\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
#4 C:\xampp\htdocs\proyectosistema\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#5 C:\xampp\htdocs\proyectosistema\system\Model.php(840): CodeIgniter\Database\BaseBuilder->get()
#6 C:\xampp\htdocs\proyectosistema\app\Models\Users.php(21): CodeIgniter\Model->__call('get', Array)
#7 C:\xampp\htdocs\proyectosistema\app\Controllers\Login.php(24): App\Models\Users->obtenerUsuario('admin123')
#8 C:\xampp\htdocs\proyectosistema\system\CodeIgniter.php(934): App\Controllers\Login->acceder()
#9 C:\xampp\htdocs\proyectosistema\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Login))
#10 C:\xampp\htdocs\proyectosistema\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\proyectosistema\index.php(67): CodeIgniter\CodeIgniter->run()
#12 {main}

Next mysqli_sql_exception: MySQL server has gone away in C:\xampp\htdocs\proyectosistema\system\Database\MySQLi\Connection.php:174
Stack trace:
#0 C:\xampp\htdocs\proyectosistema\system\Database\MySQLi\Connection.php(174): mysqli->real_connect('localhost', 'dscriptn_root', 'AkJkSzpj123', 'dscriptn_db_sis...', 3306, '', 0)
#1 C:\xampp\htdocs\proyectosistema\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\proyectosistema\system\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\proyectosistema\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\xampp\htdocs\proyectosistema\system\Model.php(840): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\proyectosistema\app\Models\Users.php(21): CodeIgniter\Model->__call('get', Array)
#6 C:\xampp\htdocs\proyectosistema\app\Controllers\Login.php(24): App\Models\Users->obtenerUsuario('admin123')
#7 C:\xampp\htdocs\proyectosistema\system\CodeIgniter.php(934): App\Controllers\Login->acceder()
#8 C:\xampp\htdocs\proyectosistema\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Login))
#9 C:\xampp\htdocs\proyectosistema\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp\htdocs\proyectosistema\index.php(67): CodeIgniter\CodeIgniter->run()
#11 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: MySQL server has gone away in C:\xampp\htdocs\proyectosistema\system\Database\MySQLi\Connection.php:218
Stack trace:
#0 C:\xampp\htdocs\proyectosistema\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\proyectosistema\system\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\proyectosistema\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 C:\xampp\htdocs\proyectosistema\system\Model.php(840): CodeIgniter\Database\BaseBuilder->get()
#4 C:\xampp\htdocs\proyectosistema\app\Models\Users.php(21): CodeIgniter\Model->__call('get', Array)
#5 C:\xampp\htdocs\proyectosistema\app\Controllers\Login.php(24): App\Models\Users->obtenerUsuario('admin123')
#6 C:\xampp\htdocs\proyectosistema\system\CodeIgniter.php(934): App\Controllers\Login->acceder()
#7 C:\xampp\htdocs\proyectosistema\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Login))
#8 C:\xampp\htdocs\proyectosistema\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\proyectosistema\index.php(67): CodeIgniter\CodeIgniter->run()
#10 {main}
CRITICAL - 2023-08-01 01:49:34 --> Maximum execution time of 120 seconds exceeded
in SYSTEMPATH\Debug\Exceptions.php on line 170.
 1 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
CRITICAL - 2023-08-01 01:49:34 --> Unable to connect to the database.
Main connection [MySQLi]: MySQL server has gone away
in SYSTEMPATH\Database\BaseConnection.php on line 427.
 1 SYSTEMPATH\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `usuarios`
WHERE `usuario` = :usuario:', [...], false)
 3 SYSTEMPATH\Model.php(840): CodeIgniter\Database\BaseBuilder->get()
 4 APPPATH\Models\Users.php(21): CodeIgniter\Model->__call('get', [])
 5 APPPATH\Controllers\Login.php(24): App\Models\Users->obtenerUsuario('admin123')
 6 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Login->acceder()
 7 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Login))
 8 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
ERROR - 2023-08-01 01:50:42 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'dscriptn_root'@'localhost' (using password: YES) in C:\xampp\htdocs\proyectosistema\system\Database\MySQLi\Connection.php:174
Stack trace:
#0 C:\xampp\htdocs\proyectosistema\system\Database\MySQLi\Connection.php(174): mysqli->real_connect('localhost', 'dscriptn_root', 'AkJkSzpj123', 'dscriptn_db_sis...', 3306, '', 0)
#1 C:\xampp\htdocs\proyectosistema\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\proyectosistema\system\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\proyectosistema\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\xampp\htdocs\proyectosistema\system\Model.php(840): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\proyectosistema\app\Models\Users.php(21): CodeIgniter\Model->__call('get', Array)
#6 C:\xampp\htdocs\proyectosistema\app\Controllers\Login.php(24): App\Models\Users->obtenerUsuario('admin123')
#7 C:\xampp\htdocs\proyectosistema\system\CodeIgniter.php(934): App\Controllers\Login->acceder()
#8 C:\xampp\htdocs\proyectosistema\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Login))
#9 C:\xampp\htdocs\proyectosistema\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp\htdocs\proyectosistema\index.php(67): CodeIgniter\CodeIgniter->run()
#11 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: YES) in C:\xampp\htdocs\proyectosistema\system\Database\MySQLi\Connection.php:218
Stack trace:
#0 C:\xampp\htdocs\proyectosistema\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\proyectosistema\system\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\proyectosistema\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 C:\xampp\htdocs\proyectosistema\system\Model.php(840): CodeIgniter\Database\BaseBuilder->get()
#4 C:\xampp\htdocs\proyectosistema\app\Models\Users.php(21): CodeIgniter\Model->__call('get', Array)
#5 C:\xampp\htdocs\proyectosistema\app\Controllers\Login.php(24): App\Models\Users->obtenerUsuario('admin123')
#6 C:\xampp\htdocs\proyectosistema\system\CodeIgniter.php(934): App\Controllers\Login->acceder()
#7 C:\xampp\htdocs\proyectosistema\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Login))
#8 C:\xampp\htdocs\proyectosistema\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\proyectosistema\index.php(67): CodeIgniter\CodeIgniter->run()
#10 {main}
CRITICAL - 2023-08-01 01:50:42 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
in SYSTEMPATH\Database\BaseConnection.php on line 427.
 1 SYSTEMPATH\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `usuarios`
WHERE `usuario` = :usuario:', [...], false)
 3 SYSTEMPATH\Model.php(840): CodeIgniter\Database\BaseBuilder->get()
 4 APPPATH\Models\Users.php(21): CodeIgniter\Model->__call('get', [])
 5 APPPATH\Controllers\Login.php(24): App\Models\Users->obtenerUsuario('admin123')
 6 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Login->acceder()
 7 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Login))
 8 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
ERROR - 2023-08-01 02:21:15 --> mysqli_sql_exception: Cannot delete or update a parent row: a foreign key constraint fails (`dscriptn_db_sistema`.`detalle_cotizacion`, CONSTRAINT `fk_detallescotizacion_productos1` FOREIGN KEY (`id_producto`) REFERENCES `productos` (`id`)) in C:\xampp\htdocs\proyectosistema\system\Database\MySQLi\Connection.php:295
Stack trace:
#0 C:\xampp\htdocs\proyectosistema\system\Database\MySQLi\Connection.php(295): mysqli->query('DELETE FROM `pr...', 0)
#1 C:\xampp\htdocs\proyectosistema\system\Database\BaseConnection.php(691): CodeIgniter\Database\MySQLi\Connection->execute('DELETE FROM `pr...')
#2 C:\xampp\htdocs\proyectosistema\system\Database\BaseConnection.php(605): CodeIgniter\Database\BaseConnection->simpleQuery('DELETE FROM `pr...')
#3 C:\xampp\htdocs\proyectosistema\system\Database\BaseBuilder.php(2791): CodeIgniter\Database\BaseConnection->query('DELETE FROM `pr...', Array, false)
#4 C:\xampp\htdocs\proyectosistema\system\Model.php(456): CodeIgniter\Database\BaseBuilder->delete()
#5 C:\xampp\htdocs\proyectosistema\system\BaseModel.php(1065): CodeIgniter\Model->doDelete(Array, false)
#6 C:\xampp\htdocs\proyectosistema\app\Controllers\Producto.php(204): CodeIgniter\BaseModel->delete(Array)
#7 C:\xampp\htdocs\proyectosistema\system\CodeIgniter.php(934): App\Controllers\Producto->eliminar('6')
#8 C:\xampp\htdocs\proyectosistema\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Producto))
#9 C:\xampp\htdocs\proyectosistema\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp\htdocs\proyectosistema\index.php(67): CodeIgniter\CodeIgniter->run()
#11 {main}
CRITICAL - 2023-08-01 02:21:15 --> Cannot delete or update a parent row: a foreign key constraint fails (`dscriptn_db_sistema`.`detalle_cotizacion`, CONSTRAINT `fk_detallescotizacion_productos1` FOREIGN KEY (`id_producto`) REFERENCES `productos` (`id`))
in SYSTEMPATH\Database\MySQLi\Connection.php on line 295.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(295): mysqli->query('DELETE FROM `productos`
WHERE `id` = \'6\'
AND `id` IN (\'6\')', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(691): CodeIgniter\Database\MySQLi\Connection->execute('DELETE FROM `productos`
WHERE `id` = \'6\'
AND `id` IN (\'6\')')
 3 SYSTEMPATH\Database\BaseConnection.php(605): CodeIgniter\Database\BaseConnection->simpleQuery('DELETE FROM `productos`
WHERE `id` = \'6\'
AND `id` IN (\'6\')')
 4 SYSTEMPATH\Database\BaseBuilder.php(2791): CodeIgniter\Database\BaseConnection->query('DELETE FROM `productos`
WHERE `id` = :id:
AND `id` IN :id.1:', [...], false)
 5 SYSTEMPATH\Model.php(456): CodeIgniter\Database\BaseBuilder->delete()
 6 SYSTEMPATH\BaseModel.php(1065): CodeIgniter\Model->doDelete([...], false)
 7 APPPATH\Controllers\Producto.php(204): CodeIgniter\BaseModel->delete([...])
 8 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Producto->eliminar('6')
 9 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Producto))
10 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
11 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
ERROR - 2023-08-01 02:49:41 --> mysqli_sql_exception: Cannot delete or update a parent row: a foreign key constraint fails (`dscriptn_db_sistema`.`compras`, CONSTRAINT `fk_compras_personas_prov1` FOREIGN KEY (`id_per_prov`) REFERENCES `personas` (`id`)) in C:\xampp\htdocs\proyectosistema\system\Database\MySQLi\Connection.php:295
Stack trace:
#0 C:\xampp\htdocs\proyectosistema\system\Database\MySQLi\Connection.php(295): mysqli->query('DELETE FROM `pe...', 0)
#1 C:\xampp\htdocs\proyectosistema\system\Database\BaseConnection.php(691): CodeIgniter\Database\MySQLi\Connection->execute('DELETE FROM `pe...')
#2 C:\xampp\htdocs\proyectosistema\system\Database\BaseConnection.php(605): CodeIgniter\Database\BaseConnection->simpleQuery('DELETE FROM `pe...')
#3 C:\xampp\htdocs\proyectosistema\system\Database\BaseBuilder.php(2791): CodeIgniter\Database\BaseConnection->query('DELETE FROM `pe...', Array, false)
#4 C:\xampp\htdocs\proyectosistema\system\Model.php(456): CodeIgniter\Database\BaseBuilder->delete()
#5 C:\xampp\htdocs\proyectosistema\system\BaseModel.php(1065): CodeIgniter\Model->doDelete(Array, false)
#6 C:\xampp\htdocs\proyectosistema\app\Controllers\Persona.php(396): CodeIgniter\BaseModel->delete(Array)
#7 C:\xampp\htdocs\proyectosistema\system\CodeIgniter.php(934): App\Controllers\Persona->eliminar('3')
#8 C:\xampp\htdocs\proyectosistema\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Persona))
#9 C:\xampp\htdocs\proyectosistema\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp\htdocs\proyectosistema\index.php(67): CodeIgniter\CodeIgniter->run()
#11 {main}
CRITICAL - 2023-08-01 02:49:41 --> Cannot delete or update a parent row: a foreign key constraint fails (`dscriptn_db_sistema`.`compras`, CONSTRAINT `fk_compras_personas_prov1` FOREIGN KEY (`id_per_prov`) REFERENCES `personas` (`id`))
in SYSTEMPATH\Database\MySQLi\Connection.php on line 295.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(295): mysqli->query('DELETE FROM `personas`
WHERE `id` = \'3\'
AND `id` IN (\'3\')', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(691): CodeIgniter\Database\MySQLi\Connection->execute('DELETE FROM `personas`
WHERE `id` = \'3\'
AND `id` IN (\'3\')')
 3 SYSTEMPATH\Database\BaseConnection.php(605): CodeIgniter\Database\BaseConnection->simpleQuery('DELETE FROM `personas`
WHERE `id` = \'3\'
AND `id` IN (\'3\')')
 4 SYSTEMPATH\Database\BaseBuilder.php(2791): CodeIgniter\Database\BaseConnection->query('DELETE FROM `personas`
WHERE `id` = :id:
AND `id` IN :id.1:', [...], false)
 5 SYSTEMPATH\Model.php(456): CodeIgniter\Database\BaseBuilder->delete()
 6 SYSTEMPATH\BaseModel.php(1065): CodeIgniter\Model->doDelete([...], false)
 7 APPPATH\Controllers\Persona.php(396): CodeIgniter\BaseModel->delete([...])
 8 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Persona->eliminar('3')
 9 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Persona))
10 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
11 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
ERROR - 2023-08-01 02:54:41 --> mysqli_sql_exception: Cannot delete or update a parent row: a foreign key constraint fails (`dscriptn_db_sistema`.`cotizaciones`, CONSTRAINT `fk_cotizaciones_vendedor1` FOREIGN KEY (`id_vendedor`) REFERENCES `personas` (`id`)) in C:\xampp\htdocs\proyectosistema\system\Database\MySQLi\Connection.php:295
Stack trace:
#0 C:\xampp\htdocs\proyectosistema\system\Database\MySQLi\Connection.php(295): mysqli->query('DELETE FROM `pe...', 0)
#1 C:\xampp\htdocs\proyectosistema\system\Database\BaseConnection.php(691): CodeIgniter\Database\MySQLi\Connection->execute('DELETE FROM `pe...')
#2 C:\xampp\htdocs\proyectosistema\system\Database\BaseConnection.php(605): CodeIgniter\Database\BaseConnection->simpleQuery('DELETE FROM `pe...')
#3 C:\xampp\htdocs\proyectosistema\system\Database\BaseBuilder.php(2791): CodeIgniter\Database\BaseConnection->query('DELETE FROM `pe...', Array, false)
#4 C:\xampp\htdocs\proyectosistema\system\Model.php(456): CodeIgniter\Database\BaseBuilder->delete()
#5 C:\xampp\htdocs\proyectosistema\system\BaseModel.php(1065): CodeIgniter\Model->doDelete(Array, false)
#6 C:\xampp\htdocs\proyectosistema\app\Controllers\Persona.php(418): CodeIgniter\BaseModel->delete(Array)
#7 C:\xampp\htdocs\proyectosistema\system\CodeIgniter.php(934): App\Controllers\Persona->eliminar('4')
#8 C:\xampp\htdocs\proyectosistema\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Persona))
#9 C:\xampp\htdocs\proyectosistema\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp\htdocs\proyectosistema\index.php(67): CodeIgniter\CodeIgniter->run()
#11 {main}
CRITICAL - 2023-08-01 02:54:41 --> Cannot delete or update a parent row: a foreign key constraint fails (`dscriptn_db_sistema`.`cotizaciones`, CONSTRAINT `fk_cotizaciones_vendedor1` FOREIGN KEY (`id_vendedor`) REFERENCES `personas` (`id`))
in SYSTEMPATH\Database\MySQLi\Connection.php on line 295.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(295): mysqli->query('DELETE FROM `personas`
WHERE `id` = \'4\'
AND `id` IN (\'4\')', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(691): CodeIgniter\Database\MySQLi\Connection->execute('DELETE FROM `personas`
WHERE `id` = \'4\'
AND `id` IN (\'4\')')
 3 SYSTEMPATH\Database\BaseConnection.php(605): CodeIgniter\Database\BaseConnection->simpleQuery('DELETE FROM `personas`
WHERE `id` = \'4\'
AND `id` IN (\'4\')')
 4 SYSTEMPATH\Database\BaseBuilder.php(2791): CodeIgniter\Database\BaseConnection->query('DELETE FROM `personas`
WHERE `id` = :id:
AND `id` IN :id.1:', [...], false)
 5 SYSTEMPATH\Model.php(456): CodeIgniter\Database\BaseBuilder->delete()
 6 SYSTEMPATH\BaseModel.php(1065): CodeIgniter\Model->doDelete([...], false)
 7 APPPATH\Controllers\Persona.php(418): CodeIgniter\BaseModel->delete([...])
 8 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Persona->eliminar('4')
 9 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Persona))
10 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
11 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
ERROR - 2023-08-01 02:55:23 --> mysqli_sql_exception: Cannot delete or update a parent row: a foreign key constraint fails (`dscriptn_db_sistema`.`cotizaciones`, CONSTRAINT `fk_cotizaciones_vendedor1` FOREIGN KEY (`id_vendedor`) REFERENCES `personas` (`id`)) in C:\xampp\htdocs\proyectosistema\system\Database\MySQLi\Connection.php:295
Stack trace:
#0 C:\xampp\htdocs\proyectosistema\system\Database\MySQLi\Connection.php(295): mysqli->query('DELETE FROM `pe...', 0)
#1 C:\xampp\htdocs\proyectosistema\system\Database\BaseConnection.php(691): CodeIgniter\Database\MySQLi\Connection->execute('DELETE FROM `pe...')
#2 C:\xampp\htdocs\proyectosistema\system\Database\BaseConnection.php(605): CodeIgniter\Database\BaseConnection->simpleQuery('DELETE FROM `pe...')
#3 C:\xampp\htdocs\proyectosistema\system\Database\BaseBuilder.php(2791): CodeIgniter\Database\BaseConnection->query('DELETE FROM `pe...', Array, false)
#4 C:\xampp\htdocs\proyectosistema\system\Model.php(456): CodeIgniter\Database\BaseBuilder->delete()
#5 C:\xampp\htdocs\proyectosistema\system\BaseModel.php(1065): CodeIgniter\Model->doDelete(Array, false)
#6 C:\xampp\htdocs\proyectosistema\app\Controllers\Persona.php(418): CodeIgniter\BaseModel->delete(Array)
#7 C:\xampp\htdocs\proyectosistema\system\CodeIgniter.php(934): App\Controllers\Persona->eliminar('4')
#8 C:\xampp\htdocs\proyectosistema\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Persona))
#9 C:\xampp\htdocs\proyectosistema\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp\htdocs\proyectosistema\index.php(67): CodeIgniter\CodeIgniter->run()
#11 {main}
CRITICAL - 2023-08-01 02:55:23 --> Cannot delete or update a parent row: a foreign key constraint fails (`dscriptn_db_sistema`.`cotizaciones`, CONSTRAINT `fk_cotizaciones_vendedor1` FOREIGN KEY (`id_vendedor`) REFERENCES `personas` (`id`))
in SYSTEMPATH\Database\MySQLi\Connection.php on line 295.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(295): mysqli->query('DELETE FROM `personas`
WHERE `id` = \'4\'
AND `id` IN (\'4\')', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(691): CodeIgniter\Database\MySQLi\Connection->execute('DELETE FROM `personas`
WHERE `id` = \'4\'
AND `id` IN (\'4\')')
 3 SYSTEMPATH\Database\BaseConnection.php(605): CodeIgniter\Database\BaseConnection->simpleQuery('DELETE FROM `personas`
WHERE `id` = \'4\'
AND `id` IN (\'4\')')
 4 SYSTEMPATH\Database\BaseBuilder.php(2791): CodeIgniter\Database\BaseConnection->query('DELETE FROM `personas`
WHERE `id` = :id:
AND `id` IN :id.1:', [...], false)
 5 SYSTEMPATH\Model.php(456): CodeIgniter\Database\BaseBuilder->delete()
 6 SYSTEMPATH\BaseModel.php(1065): CodeIgniter\Model->doDelete([...], false)
 7 APPPATH\Controllers\Persona.php(418): CodeIgniter\BaseModel->delete([...])
 8 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Persona->eliminar('4')
 9 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Persona))
10 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
11 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
